[package]
name = "hist"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "*"
serde = { version = "*", features = ["derive"] }
csv = "*"
structopt = "*"
fst = "*"
